tittle: "Rayde Prosperin MPOUAVOULI"
logo: "C:/Users/Visiteur/Documents/Cle USB/10eme anniverssaire FMC/WhatsApp Image 2025-10-12 à 23.13.16_e7960d6b.jpg"
description: "Portfolio Projet Finance et synthèse cours"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
